Feat/popover
fincity-india/nocode-ui pull request #116
Opened 2023-03-06 05:48 UTC by Tarun-Jangra4

2023-03-08 10:56 UTC, serialcoder13 requested changes
Please make the requested changes.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Popover/PopoverStyle.tsx
> +			background-color: black;
Move this background-color to the styleproperties

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Popover/PopoverStyle.tsx
> +		}
I think these commented lines are required to give the border around the popover container. Remove width and height. Move border-radius, border and background-color (with no default value) to the style properties.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Popover/popoverProperties.ts
> +	},
Also add the border group to the popover container and add it to the component.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Popover/popoverProperties.ts
> +	COMMON_COMPONENT_PROPERTIES.visibility,
add close on leave option.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Portal.tsx
>  const Portal: React.FC<Props> = ({ children, parent }) => {
add an id property.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Portal.tsx
>  	const el = React.useMemo(() => document.createElement('div'), []);
Don't use the div using the memo function. Create an element only if the parent is null. Add the containing div with the id. Use the memo function to generate a UUID to associate with the newly created div.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/Portal.tsx
>  	const el = React.useMemo(() => document.createElement('div'), []);
On click of this div also the popover should be closed.

2023-03-08 10:56 UTC, serialcoder13 commented on ui-app/client/src/components/util/getPositions.ts
> +export default function getPositions(position: String, boxRect: DOMRect, popoverRect: DOMRect) {
The position data type has to be an enum and create an enum here and use it in the component.

2023-03-31 06:31 UTC, raja-avinash approved these changes
LGTM

2023-03-31 06:31 UTC, merged