deleteWithEventOptionContextMenu
fincity-india/nocode-ui pull request #707
Opened 2024-02-14 09:44 UTC by Sumitabhbiswas

2024-02-21 08:20 UTC, shagil786 requested changes

2024-02-21 08:20 UTC, shagil786 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +
@Sumitabhbiswas can u please get the map of event keys instead of arrays itself?

2024-02-23 10:42 UTC, serialcoder13 requested changes
Please make the suggested changes

2024-02-23 10:42 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +			};
Create a duplicate instead of spread.

2024-02-23 10:42 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +			});
change this to a for loop

2024-02-27 12:22 UTC, serialcoder13 requested changes
Please make the changes

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
send false for the deleteExisting parameter. And make the changes in the function to handle the missing definition objects.

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +	private _changeKeys(clipObj: ClipboardObject, pageDef?: PageDefinition): ClipboardObject {
Remove pageDef Parameter

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +						message: 'Do you want to Ignore the incoming event functions?',
Select an operation to handle existing functions

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +										clipObj.eventObjects,
Don't send eventObjects in this case.

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +		const index: { [key: string]: string } = {};
Move the two lines above after if.

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +			if (!cdDef) {
return early if there are no properties

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +								const allEventKeys: Array<string> = Object.values(
No need to changeeventkeys

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +			if ((pageDef as any)['id'] !== clipObj.pageId) {
if and else condition interchange.

2024-02-27 12:22 UTC, serialcoder13 commented on ui-app/client/src/components/PageEditor/functions/PageOperations.ts
> +					this._dropOn(
move this else into if and viceversa

2024-02-29 12:56 UTC, merged